#############################################################################
# Makefile for building: MineSwee
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  MineSwee.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile MineSwee.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../Qt5.7.0/5.7/gcc_64/include -I../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets -I../../../../Qt5.7.0/5.7/gcc_64/include/QtGui -I../../../../Qt5.7.0/5.7/gcc_64/include/QtCore -I. -I. -I../../../../Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MineSwee1.0.0
DISTDIR = /home/jsdoing/Development/QT_Develop/project/MineSwee/.tmp/MineSwee1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/jsdoing/Qt5.7.0/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/jsdoing/Qt5.7.0/5.7/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		item.cpp qrc_resource.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		item.o \
		qrc_resource.o \
		moc_mainwindow.o
DIST          = ../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		MineSwee.pro mainwindow.h \
		item.h main.cpp \
		mainwindow.cpp \
		item.cpp
QMAKE_TARGET  = MineSwee
DESTDIR       = 
TARGET        = MineSwee


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MineSwee.pro ../../../../Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		MineSwee.pro \
		resource.qrc \
		../../../../Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.prl \
		../../../../Qt5.7.0/5.7/gcc_64/lib/libQt5Gui.prl \
		../../../../Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile MineSwee.pro
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf:
../../../../Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf:
MineSwee.pro:
resource.qrc:
../../../../Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.prl:
../../../../Qt5.7.0/5.7/gcc_64/lib/libQt5Gui.prl:
../../../../Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MineSwee.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resource.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h item.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp item.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		../../../../Qt5.7.0/5.7/gcc_64/bin/rcc \
		bomb.png \
		flag.png
	/home/jsdoing/Qt5.7.0/5.7/gcc_64/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: item.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/QPoint \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/QMainWindow \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qfont.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qevent.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qurl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qfile.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qicon.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/QTimer \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbasictimer.h \
		mainwindow.h \
		../../../../Qt5.7.0/5.7/gcc_64/bin/moc
	/home/jsdoing/Qt5.7.0/5.7/gcc_64/bin/moc $(DEFINES) -I/home/jsdoing/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++ -I/home/jsdoing/Development/QT_Develop/project/MineSwee -I/home/jsdoing/Qt5.7.0/5.7/gcc_64/include -I/home/jsdoing/Qt5.7.0/5.7/gcc_64/include/QtWidgets -I/home/jsdoing/Qt5.7.0/5.7/gcc_64/include/QtGui -I/home/jsdoing/Qt5.7.0/5.7/gcc_64/include/QtCore -I/usr/local/arm/5.4.0/usr/arm-none-linux-gnueabi/include/c++/5.4.0 -I/usr/local/arm/5.4.0/usr/arm-none-linux-gnueabi/include/c++/5.4.0/arm-none-linux-gnueabi -I/usr/local/arm/5.4.0/usr/arm-none-linux-gnueabi/include/c++/5.4.0/backward -I/usr/local/arm/5.4.0/usr/lib/gcc/arm-none-linux-gnueabi/5.4.0/include -I/usr/local/arm/5.4.0/usr/lib/gcc/arm-none-linux-gnueabi/5.4.0/include-fixed -I/usr/local/arm/5.4.0/usr/arm-none-linux-gnueabi/include -I/usr/local/arm/5.4.0/usr/arm-none-linux-gnueabi/sysroot/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../../Qt5.7.0/5.7/gcc_64/bin/uic
	/home/jsdoing/Qt5.7.0/5.7/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		item.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/QPoint \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/QMainWindow \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qfont.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qevent.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qurl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qfile.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qicon.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/QTimer \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbasictimer.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/QApplication \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qapplication.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		item.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/QPoint \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/QMainWindow \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qfont.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qevent.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qurl.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qfile.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qicon.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/QTimer \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbasictimer.h \
		ui_mainwindow.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/QPaintEvent \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/QPainter \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpainter.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qtextoption.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtGui/qpen.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/QTime \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/QMessageBox \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtWidgets/qdialog.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

item.o: item.cpp item.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/QPoint \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../../Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o item.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

